---
title: "OZdatasets"
author: "Kristy Robledo, Jessica Lee, Alyce Russell, Tanya Prvan"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE )
```

## Summary table
```{r}
library(DT)
df<-rbind(c("ozflights", "transport", "package", "Flight data"),
          c("ozroaddeaths", "transport", "package", "Road deaths"),
          c("vehicles", "transport", "link", "Vehicle use"),
          c("beaches", "environment", "link", "Sydney beach data"),
          c("river", "environment", "link", "River and rainfall data"),
          c("birds", "environment", "link", "Data about Australian birds"),
          c("atlas", "environment", "link", "Atlas of Australian biodiversity"),
          c("fires", "environment", "link", "Bush fire data"),
          c("ozbabynames", "demographics", "package", "Baby names in Australia"),
          c("eechidna", "demographics", "package", "Election and census data"),
          c("ozdata", "demographics", "package", "Australian economic data"),
          c("raustats", "demographics", "package-BROKEN??", "Household survey"),
          c("longitudinal", "demographics", "link", "Longitudinal"),
          c("marriageequality", "demographics", "link", "Data from the 2017 marriage equality survey"),
          c("aflinfo", "sport", "package", "AFL data"),
          c("fitzRoy", "sport", "package", "AFL data"),
          c("cricketdata", "sport", "package", "Cricket data"),
          c("ozmaps", "maps", "package", "Maps of Australia"),
          c("ozdates", "misc", "package", "Maps of Australia"),
          c("smokeybear", "", "package", ""), # TO ADD
          c("learningtower", "", "package", "") # TO ADD
)

DT::datatable(df, colnames = c("Name","Topic","Package/Link","Data explanation"))

```

## Transport 

```{r child="transport.Rmd"}
```

## Environmental

```{r child="enviro.Rmd"}
```

## Demographics

```{r child="demo.Rmd"}
```

## Sport

```{r child="sport.Rmd"}
```

## Maps

The [readme file](https://github.com/mdsumner/ozmaps/) is very descriptive for how to create Maps of australia in ggplot. 

```{r, eval = FALSE}
install.packages("ozmaps")
```

```{r, eval = TRUE}
library(ozmaps)

```

## Miscellaneous 

### Ozdates

Important australian dates, like public holidays etc. The readme on [github](https://deanmarchiori.github.io/ozdates/) explains how to use. 

```{r, eval=FALSE}
devtools::install_github("deanmarchiori/ozdates")
```


